name: check site alive
kind: test.availability

trigger:
  every: 5m

args: []

steps:
  - name: http ping
    function: http.ping_get
    with:
      url: https://google.com

  - name: test post
    function: http.post
    with:
      url: https://example.com


  - name: test post
    function: http.post
    with:
      url: https://example.com
  
  - name: test post
    function: http.post
    with:
      url: https://example.com